### ISSUE TITLE
Chapter 1, Docker Recipe, 502 Bad Gateway

### ISSUE THREAD

**Issue by rossm6** [PacktPublishing/Django-2-Web-Development-Cookbook-Third-Edition#1]
Hi

I'm new to web development and thought this book looked great to help me with Django.  But I'm stuck on the first chapter already and can't see my fault.  Please help !

After cloning the repo, I navigate to the root of the chapter_1/myproject_docker.  Before running any commands I have created this line in /etc/hosts (on my Ubuntu 18.04 OS)

127.0.0.1       myproject.local media.myproject.local static.myproject.local

And I have made sure the dev script is executable.

I then build the docker image with -

run ./bin/dev build 

And finally I run -

MYSQL_USER=myproject_user MYSQL_PASSWORD=pass1234 ./bin/dev up -d

It creates the containers fine.  However when i go to "http://myproject.local" in my browser I get "502 Bad Gateway - nginx/1.17.2" 

Any ideas ?

**Comment by thebpmgroup** [comment]
I had this. I had missed the step on adding the entry into the hosts file. See page 30. You need entries for myproject.local, media.myproject.local and static.project.local

Also NGINX needs to know where to forward the request on to, and this is done through a virtual port, see page 27.

Also make sure you have set your SITE_HOST environment variable in the bin/dev.sh or bin/dev file (depending on if you used an extension)
